spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:kunden.sql


# By design, the in-memory database is volatile, and results in data loss after application restart.
# We can change that behavior by using file-based storage. To do this we need to update the spring.datasource.url property:
#spring:
#  datasource:
#    url: jdbc:h2:file:/data/demo
